export const ITEMS_FETCH_REQUEST = "items/ITEMS_FETCH_REQUEST";
export const ITEMS_FETCH_SUCCEEDED = "items/ITEMS_FETCH_SUCCEEDED";
export const ITEMS_FETCH_FINISHED = "items/ITEMS_FETCH_FINISHED";
export const ITEMS_FETCH_FAILED = "items/ITEMS_FETCH_FAILED";
